### ISSUE TITLE
API Update from March 9, 2021 introduced new fields in the Update class

### ISSUE THREAD

**Issue by punkx** [bot4s/telegram#118]
From the API docs:

> Added two new update types
> 
> Added updates about member status changes in chats, represented by the class ChatMemberUpdated and the fields my_chat_member and chat_member in the Update class. The bot must be an administrator in the chat to receive chat_member updates about other chat members. By default, only my_chat_member updates about the bot itself are received.

In a private chat with the bot a user can stop and restart the bot now. The resulting JSON messages can not be parsed and result in an exception.

JSON:
```
{
    "ok": true,
    "result": [
        {
            "update_id": 123456790,
            "my_chat_member": {
                "chat": {
                    "id": 234567890,
                    "first_name": "FName",
                    "username": "UsrNm",
                    "type": "private"
                },
                "from": {
                    "id": 234567890,
                    "is_bot": false,
                    "first_name": "FName",
                    "username": "UsrNm",
                    "language_code": "de"
                },
                "date": 1629140497,
                "old_chat_member": {
                    "user": {
                        "id": 3456789012,
                        "is_bot": true,
                        "first_name": "BFnme",
                        "username": "BotUName"
                    },
                    "status": "member"
                },
                "new_chat_member": {
                    "user": {
                        "id": 3456789012,
                        "is_bot": true,
                        "first_name": "BFnma",
                        "username": "BotUName"
                    },
                    "status": "kicked",
                    "until_date": 0
                }
            }
        }
    ]
}
```

Exception:
```
21:02:22.234 [scala-execution-context-global-186] ERROR c.b.telegram.clients.AkkaHttpClient - RESPONSE eaa3d557-aa22-4799-be9a-b04296a43107 {}
java.lang.IllegalArgumentException: requirement failed: Exactly one of the optional fields should be used
        at scala.Predef$.require(Predef.scala:281)
        at com.bot4s.telegram.models.Update.<init>(Update.scala:48)
        at com.bot4s.telegram.marshalling.CirceDecoders$anon$lazy$macro$27$1$anon$macro$25$1.from(CirceDecoders.scala:139)
        at com.bot4s.telegram.marshalling.CirceDecoders$anon$lazy$macro$27$1$anon$macro$25$1.from(CirceDecoders.scala:139)
        at shapeless.LabelledGeneric$$anon$1.from(generic.scala:229)
        at shapeless.LabelledGeneric$$anon$1.from(generic.scala:226)
        at io.circe.generic.decoding.DerivedDecoder$$anon$1.apply(DerivedDecoder.scala:15)
        at io.circe.SeqDecoder.apply(SeqDecoder.scala:17)
        at io.circe.Decoder$$anon$38.tryDecode(Decoder.scala:854)
        at com.bot4s.telegram.marshalling.CirceDecoders$anon$lazy$macro$15$12$$anon$108.apply(CirceDecoders.scala:143)
        at io.circe.generic.decoding.DerivedDecoder$$anon$1.apply(DerivedDecoder.scala:14)
        at io.circe.Json.as(Json.scala:106)
        at com.bot4s.telegram.marshalling.package$.$anonfun$fromJson$2(package.scala:39)
        at scala.util.Either.fold(Either.scala:191)
        at com.bot4s.telegram.marshalling.package$.fromJson(package.scala:38)
        at com.bot4s.telegram.marshalling.AkkaHttpMarshalling$.$anonfun$camelCaseJsonUnmarshaller$1(AkkaHttpMarshalling.scala:18)
        at akka.http.scaladsl.util.FastFuture$.$anonfun$map$1(FastFuture.scala:23)
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
        at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
        at akka.http.scaladsl.util.FastFuture$.map$extension(FastFuture.scala:23)
        at akka.http.scaladsl.unmarshalling.Unmarshaller.$anonfun$map$3(Unmarshaller.scala:26)
        at akka.http.scaladsl.unmarshalling.Unmarshaller.$anonfun$transform$3(Unmarshaller.scala:23)
        at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:58)
        at akka.http.scaladsl.unmarshalling.Unmarshal.to(Unmarshal.scala:25)
        at com.bot4s.telegram.clients.AkkaHttpClient.$anonfun$sendRequest$3(AkkaHttpClient.scala:39)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
21:02:22.235 [scala-execution-context-global-186] ERROR actors.BotInterface - GetUpdates failed

```

**Comment by punkx** [comment]
Just found out I did not update to the newest version, where the issue is resolved already. Feel free to delete this issue.
