### ISSUE TITLE
TelegramApiException: Not Found

### ISSUE THREAD

**Issue by CHEguK** [bot4s/telegram#125]
Yesterday It works, today not. I don't have a single thought

Code:

```
object Launcher extends IOApp {

  def run(args: List[String]): IO[ExitCode] = {
    val token: String = System.getenv("TOKEN")
    new EchoBot[IO](token).startPolling().map(_ => ExitCode.Success)
  }
}

class EchoBot[F[_]: Concurrent: ContextShift](token: String) extends ExampleBot[F](token) with Polling[F] with Commands[F]{

  override def receiveMessage(msg: Message): F[Unit] = {
    msg.text.fold(unit) { text =>
      val u = FormulaParser(text)
      u match {
        case Left(error) => request(SendMessage(msg.source, s"\'$text\' parsing error: $error")).void
        case Right(value) => request(SendMessage(msg.source, Evaluator(value).toString)).void
      }
    }
  }

}
```

Error:
```
14:23:54.539 [AsyncHttpClient-3-1] DEBUG org.asynchttpclient.netty.channel.NettyConnectListener - Using new Channel '[id: 0xa187ba16, L:/192.168.0.107:43684 - R:api.telegram.org/149.154.167.220:443]' for 'POST' to '/botnull/DeleteWebhook'
14:23:54.559 [AsyncHttpClient-3-1] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xa187ba16, L:/192.168.0.107:43684 - R:api.telegram.org/149.154.167.220:443] HANDSHAKEN: protocol:TLSv1.2 cipher suite:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
14:23:54.632 [AsyncHttpClient-3-1] DEBUG org.asynchttpclient.netty.handler.HttpHandler - 

Request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: UnpooledHeapByteBuf(freed))
POST /botnull/DeleteWebhook HTTP/1.1
Content-Type: application/json; charset=utf-8
accept-encoding: gzip, deflate
content-length: 4
host: api.telegram.org
accept: */*
user-agent: AHC/2.1

Response DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 404 Not Found
Server: nginx/1.18.0
Date: Wed, 03 Nov 2021 09:23:54 GMT
Content-Type: application/json
Connection: keep-alive
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Length,Content-Type,Date,Server,Connection
content-length: 55
14:23:54.679 [AsyncHttpClient-3-1] DEBUG org.asynchttpclient.netty.channel.ChannelManager - Adding key: https://api.telegram.org:443 for channel [id: 0xa187ba16, L:/192.168.0.107:43684 - R:api.telegram.org/149.154.167.220:443]
14:23:54.733 [ioapp-compute-1] ERROR com.bot4s.telegram.clients.SttpClient - RESPONSE 515db0e1-28a0-4d5a-b364-564638dd12b8 {}
com.bot4s.telegram.api.TelegramApiException: Not Found
	at com.bot4s.telegram.api.RequestHandler.processApiResponse(RequestHandler.scala:127)
	at com.bot4s.telegram.clients.SttpClient.$anonfun$sendRequest$9(SttpClient.scala:92)
	at apply @ sttp.client3.asynchttpclient.BodyFromAHC.success$1(BodyFromAHC.scala:29)
	at cancelable @ sttp.client3.impl.cats.CatsMonadAsyncError.async(CatsMonadAsyncError.scala:20)
	at map @ sttp.client3.impl.cats.CatsMonadAsyncError.map(CatsMonadAsyncError.scala:9)
	at map @ sttp.client3.impl.cats.CatsMonadAsyncError.map(CatsMonadAsyncError.scala:9)
	at map @ sttp.client3.impl.cats.CatsMonadAsyncError.map(CatsMonadAsyncError.scala:9)
	at map @ sttp.client3.impl.cats.CatsMonadAsyncError.map(CatsMonadAsyncError.scala:9)
	at cancelable @ sttp.client3.impl.cats.CatsMonadAsyncError.async(CatsMonadAsyncError.scala:20)
	at flatten @ sttp.client3.impl.cats.CatsMonadAsyncError.flatten(CatsMonadAsyncError.scala:26)
	at map @ sttp.client3.impl.cats.CatsMonadAsyncError.map(CatsMonadAsyncError.scala:9)
	at flatMap @ sttp.client3.impl.cats.CatsMonadAsyncError.flatMap(CatsMonadAsyncError.scala:12)
	at guarantee$extension @ sttp.client3.asynchttpclient.cats.AsyncHttpClientCatsBackend.send(AsyncHttpClientCatsBackend.scala:41)
	at flatMap @ sttp.client3.impl.cats.CatsMonadAsyncError.flatMap(CatsMonadAsyncError.scala:12)
	at map @ com.bot4s.telegram.clients.SttpClient.sendRequest(SttpClient.scala:91)
	at map @ com.bot4s.telegram.clients.SttpClient.sendRequest(SttpClient.scala:92)
	at flatTap @ com.bot4s.telegram.api.RequestHandler.$anonfun$apply$1(RequestHandler.scala:35)
14:23:54.737 [AsyncHttpClient-3-1] DEBUG io.netty.channel.nio.NioEventLoop - Selector.select() returned prematurely because Thread.currentThread().interrupt() was called. Use NioEventLoop.shutdownGracefully() to shutdown the NioEventLoop.
com.bot4s.telegram.api.TelegramApiException: Not Found
	at com.bot4s.telegram.api.RequestHandler.processApiResponse(RequestHandler.scala:127)
	at com.bot4s.telegram.clients.SttpClient.$anonfun$sendRequest$9(SttpClient.scala:92)
	at apply @ sttp.client3.asynchttpclient.BodyFromAHC.success$1(BodyFromAHC.scala:29)
	at cancelable @ sttp.client3.impl.cats.CatsMonadAsyncError.async(CatsMonadAsyncError.scala:20)
	at map @ sttp.client3.impl.cats.CatsMonadAsyncError.map(CatsMonadAsyncError.scala:9)
	at map @ sttp.client3.impl.cats.CatsMonadAsyncError.map(CatsMonadAsyncError.scala:9)
	at map @ sttp.client3.impl.cats.CatsMonadAsyncError.map(CatsMonadAsyncError.scala:9)
	at map @ sttp.client3.impl.cats.CatsMonadAsyncError.map(CatsMonadAsyncError.scala:9)
	at cancelable @ sttp.client3.impl.cats.CatsMonadAsyncError.async(CatsMonadAsyncError.scala:20)
	at flatten @ sttp.client3.impl.cats.CatsMonadAsyncError.flatten(CatsMonadAsyncError.scala:26)
	at map @ sttp.client3.impl.cats.CatsMonadAsyncError.map(CatsMonadAsyncError.scala:9)
	at flatMap @ sttp.client3.impl.cats.CatsMonadAsyncError.flatMap(CatsMonadAsyncError.scala:12)
	at guarantee$extension @ sttp.client3.asynchttpclient.cats.AsyncHttpClientCatsBackend.send(AsyncHttpClientCatsBackend.scala:41)
	at flatMap @ sttp.client3.impl.cats.CatsMonadAsyncError.flatMap(CatsMonadAsyncError.scala:12)
	at map @ com.bot4s.telegram.clients.SttpClient.sendRequest(SttpClient.scala:91)
	at map @ com.bot4s.telegram.clients.SttpClient.sendRequest(SttpClient.scala:92)
	at flatTap @ com.bot4s.telegram.api.RequestHandler.$anonfun$apply$1(RequestHandler.scala:35)

Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-0"
14:23:55.427 [AsyncHttpClient-timer-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : https://api.telegram.org:443 : 1
14:23:56.526 [AsyncHttpClient-timer-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : https://api.telegram.org:443 : 1
.
.
.
14:24:54.826 [AsyncHttpClient-timer-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : https://api.telegram.org:443 : 1
14:24:54.827 [AsyncHttpClient-timer-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Adding Candidate expired Channel [id: 0xa187ba16, L:/192.168.0.107:43684 - R:api.telegram.org/149.154.167.220:443] isIdleTimeoutExpired=true isRemotelyClosed=false isTtlExpired=false
14:24:54.828 [AsyncHttpClient-timer-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Closing Idle Channel [id: 0xa187ba16, L:/192.168.0.107:43684 - R:api.telegram.org/149.154.167.220:443]
14:24:54.830 [AsyncHttpClient-timer-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Closed 1 connections out of 1 in 3 ms
14:24:54.836 [AsyncHttpClient-3-1] DEBUG org.asynchttpclient.netty.handler.HttpHandler - Channel Closed: [id: 0xa187ba16, L:/192.168.0.107:43684 ! R:api.telegram.org/149.154.167.220:443] with attribute DISCARD
```

**Comment by ex0ns** [comment]
Thanks for the detailed debug log.
I don't have the time to look at this right now, but here is a few pointers:

- which version of the lib are you using ?
- In the request, I can see `POST /botnull/DeleteWebhook HTTP/1.1` this is coming from https://github.com/bot4s/telegram/blob/0e30d39ae4eee5c9f4daabec8464e6d2d5f3eb48/core/src/com/bot4s/telegram/cats/Polling.scala#L34 (I can't see your import, but I would assume that you are using the `Polling` trait from the cats package. The `null` in the URL make me think of a missing token (unless you removed it to post it on github).

I think that the `null` is coming from the `System.getenv` which is returning null if the environment variable does not exist

**Comment by CHEguK** [comment]
I've confused and thought that problem in library, but problem was in my program. Sorry
