### ISSUE TITLE
Support underscore in command name

### ISSUE THREAD

**Issue by evis** [bot4s/telegram#304]
`onCommand("set_schedule") { ... }` now fails with:

```
java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:324)
	at com.bot4s.telegram.api.declarative.CommandImplicits.stringToCommandFilter(Commands.scala:109)
	at com.bot4s.telegram.api.declarative.CommandImplicits.stringToCommandFilter$(Commands.scala:102)
```

But it's a valid command.

**Comment by ex0ns** [comment]
I will try to have a look next week, thanks for reporting
