### ISSUE TITLE
requirement failed: Exactly one of the optional fields should be used

### ISSUE THREAD

**Issue by logichno** [bot4s/telegram#321]
I am getting the following error 

```
java.lang.IllegalArgumentException: requirement failed: Exactly one of the optional fields should be used
	at scala.Predef$.require(Predef.scala:337)
	at com.bot4s.telegram.models.Update.<init>(Update.scala:61)
	at com.bot4s.telegram.marshalling.CirceDecoders$anon$lazy$macro$59$2.$anonfun$inst$macro$1$245(CirceDecoders.scala:210)
	at shapeless.Generic$$anon$1.from(generic.scala:164)
	at shapeless.LabelledGeneric$$anon$2.from(generic.scala:239)
	at shapeless.LabelledGeneric$$anon$2.from(generic.scala:236)
	at io.circe.generic.decoding.DerivedDecoder$$anon$1.apply(DerivedDecoder.scala:14)
	at com.bot4s.telegram.marshalling.CirceDecoders$$anon$79.apply(CirceDecoders.scala:214)
	at io.circe.SeqDecoder.apply(SeqDecoder.scala:19)
	at io.circe.Decoder$OptionDecoder.tryDecode(Decoder.scala:973)
	at com.bot4s.telegram.marshalling.CirceDecoders$anon$lazy$macro$23$10$$anon$81.apply(CirceDecoders.scala:228)
	at io.circe.generic.decoding.DerivedDecoder$$anon$1.apply(DerivedDecoder.scala:13)
	at io.circe.Json.as(Json.scala:107)
	at com.bot4s.telegram.marshalling.package$.$anonfun$fromJson$2(package.scala:35)
	at scala.util.Either.fold(Either.scala:189)
	at com.bot4s.telegram.marshalling.package$.fromJson(package.scala:35)
	at com.bot4s.telegram.clients.SttpClient.$anonfun$asJson$1(SttpClient.scala:41)
	at sttp.client3.ResponseAs.$anonfun$map$1(ResponseAs.scala:30)
	at sttp.client3.MappedResponseAs.$anonfun$mapWithMetadata$1(ResponseAs.scala:92)
	at sttp.client3.internal.BodyFromResponseAs.$anonfun$doApply$4(BodyFromResponseAs.scala:25)
	at delay @ sttp.client3.impl.cats.CatsMonadError.eval(CatsMonadError.scala:19)
	at map @ sttp.client3.impl.cats.CatsMonadError.map(CatsMonadError.scala:9)
	at delay @ sttp.client3.impl.cats.CatsMonadError.eval(CatsMonadError.scala:19)
	at map @ sttp.client3.impl.cats.CatsMonadError.map(CatsMonadError.scala:9)
	at flatMap @ sttp.client3.impl.cats.CatsMonadError.flatMap(CatsMonadError.scala:12)
	at map @ sttp.client3.impl.cats.CatsMonadError.map(CatsMonadError.scala:9)
	at map @ sttp.client3.impl.cats.CatsMonadError.map(CatsMonadError.scala:9)
	at delay @ sttp.client3.impl.cats.CatsMonadAsyncError.$anonfun$async$1(CatsMonadAsyncError.scala:10)
	at map @ sttp.client3.impl.cats.CatsMonadAsyncError.$anonfun$async$1(CatsMonadAsyncError.scala:10)
	at async @ sttp.client3.impl.cats.CatsMonadAsyncError.async(CatsMonadAsyncError.scala:10)
	at flatten @ sttp.client3.impl.cats.CatsMonadError.flatten(CatsMonadError.scala:21)
	at map @ sttp.client3.impl.cats.CatsMonadError.map(CatsMonadError.scala:9)
	at delay @ sttp.client3.impl.cats.CatsMonadError.eval(CatsMonadError.scala:19)
	at flatten @ sttp.client3.impl.cats.CatsMonadError.flatten(CatsMonadError.scala:21)
```

Response from telegram:

```
{
  "ok": true,
  "result": [
    {
      "update_id": 111111111,
      "poll_answer": {
        "poll_id": "11111111111111111111",
        "user": {
          "id": 1111111,
          "is_bot": false,
          "first_name": "Andrey",
          "last_name": "Stolyarov",
          "username": "d10xa",
          "language_code": "en"
        },
        "option_ids": [
          0,
          1
        ]
      }
    }
  ]
}
```
<img width="611" alt="Screenshot 2023-04-15 at 23 20 03" src="https://user-images.githubusercontent.com/65854170/232251594-35aedbd8-5939-47f5-91a8-514426312414.png">

**Comment by ex0ns** [comment]
I think that the requirements on the Telegram side changed, it used to be `exactly one` but has been changed to `At most one of the optional parameters can be present in any given update.` (see https://core.telegram.org/bots/api#update)


We should change the `==` in the class to `<= ` so we handle the case that you presented. I can try to fix that tonight, otherwise feel free to open a PR, the change should be pretty simple

**Comment by ex0ns** [comment]
v5.6.4 has been released with the fix. I think that telegram must have added an field inside the `Update` case class that we don't support yet (I will try to update the library to support it), however as in the doc it says "at most one" it feels more correct to use it that way.
