### ISSUE TITLE
GetUpdates fails multiple times with an UnsupportedContentTypeException

### ISSUE THREAD

**Issue by TobsCore** [bot4s/telegram#52]
I run a bot on a server and I noticed that there are some reoccuring exceptions with the Polling. The Exception reads as follows:

```
ERROR - GetUpdates failed
akka.http.scaladsl.unmarshalling.Unmarshaller$UnsupportedContentTypeException: Unsupported Content-Type, supported: application/json
        at akka.http.scaladsl.unmarshalling.Unmarshaller$UnsupportedContentTypeException$.apply(Unmarshaller.scala:158)
        at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedFromEntityUnmarshaller$.$anonfun$forContentTypes$3(Unmarshaller.scala:114)
        at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:58)
        at akka.http.scaladsl.unmarshalling.Unmarshaller.$anonfun$transform$3(Unmarshaller.scala:23)
        at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:58)
        at akka.http.scaladsl.unmarshalling.Unmarshal.to(Unmarshal.scala:25)
        at info.mukel.telegrambot4s.clients.AkkaClient.toApiResponse(AkkaClient.scala:38)
        at info.mukel.telegrambot4s.clients.AkkaClient.$anonfun$apply$2(AkkaClient.scala:50)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

The really bad part about this is not the uncaught exception, but that the error occurs multiple times afterwards. I checked the logs and apparently the error appeared 382 times in about 12 seconds, in my example between 2:32:25 and 2:32:37. To show the frequency, I'll add an excerpt of the logs:

```
2017-12-09 02:32:25,980 ERROR h.i.t.IWINewsBot [Polling.scala:39] GetUpdates failed
2017-12-09 02:32:26,006 ERROR h.i.t.IWINewsBot [Polling.scala:39] GetUpdates failed
2017-12-09 02:32:26,035 ERROR h.i.t.IWINewsBot [Polling.scala:39] GetUpdates failed
2017-12-09 02:32:26,060 ERROR h.i.t.IWINewsBot [Polling.scala:39] GetUpdates failed
2017-12-09 02:32:26,090 ERROR h.i.t.IWINewsBot [Polling.scala:39] GetUpdates failed
2017-12-09 02:32:26,113 ERROR h.i.t.IWINewsBot [Polling.scala:39] GetUpdates failed
```

**Comment by mukel** [comment]
Can you provide more context, it's weird to receive non-JSON updates, maybe an error from the server? Rate limit exceeded?

**Comment by mukel** [comment]
It does fail when there's a problem with the connection; rare but happens. But the error if I remember correctly is different, since it can't reach the server at all. Telegram API-exceptions are properly wrapped in TelegramApiException.

Currently there's no back-off strategy implemented, it just flood the server (and logs) on error; which does not help.It's possible to implement a custom Polling strategy with exponential back-off, max retries... if you'd like to have something like that shipped by default; please leave a comment with your use case on #51.

**Comment by ex0ns** [comment]
Closing this.
Please re-open if needed
