### ISSUE TITLE
Cant run LmgtfyBot example bot

### ISSUE THREAD

**Issue by synnz** [bot4s/telegram#66]
Hello, i've got error `java.lang.NoClassDefFoundError: com/softwaremill/sttp/package$UriContext$` when i'm trying run example bot.
Dependencies
`
libraryDependencies += "com.bot4s" %% "telegram-core" % "4.0.0-RC1"
libraryDependencies += "com.bot4s" %% "telegram-akka" % "4.0.0-RC1"
libraryDependencies += "com.softwaremill.sttp" %% "core" % "1.3.8"
`

The error
`
[trace, com.bot4s.telegram.clients.SttpClient] REQUEST c67d3f8a-996b-4808-aa04-5ff784e2c700 DeleteWebhook
Exception in thread "main" java.lang.NoClassDefFoundError: com/softwaremill/sttp/package$UriContext$
	at com.bot4s.telegram.clients.SttpClient.sendRequest(SttpClient.scala:41)
	at com.bot4s.telegram.api.RequestHandler.apply(RequestHandler.scala:37)
	at com.bot4s.telegram.api.RequestHandler.apply$(RequestHandler.scala:24)
	at com.bot4s.telegram.clients.SttpClient.apply(SttpClient.scala:22)
	at com.bot4s.telegram.api.Polling.run(Polling.scala:95)
	at com.bot4s.telegram.api.Polling.run$(Polling.scala:90)
	at HelloWorld.com$bot4s$telegram$api$declarative$Commands$$super$run(HelloWorld.scala:12)
	at com.bot4s.telegram.api.declarative.Commands.run(Commands.scala:99)
	at com.bot4s.telegram.api.declarative.Commands.run$(Commands.scala:97)
	at HelloWorld.run(HelloWorld.scala:12)
	at Main$.delayedEndpoint$Main$1(Main.scala:5)
	at Main$delayedInit$body.apply(Main.scala:4)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at Main$.main(Main.scala:4)
	at Main.main(Main.scala)
Caused by: java.lang.ClassNotFoundException: com.softwaremill.sttp.package$UriContext$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more
`

**Comment by synnz** [comment]
I've deleted dep `libraryDependencies += "com.softwaremill.sttp" %% "core" % "1.3.8"` and got working bot

**Comment by mukel** [comment]
All deps updated in RC2
