### ISSUE TITLE
GetUpdates failed - MappingException: unknown error - Requirement failed

### ISSUE THREAD

**Issue by benkio** [bot4s/telegram#82]
Hi there,
I open this issue because I run at the moment two bots using this library version 3.0.16.
For bot I just extracted all the logic to drive the communication with telegram to a separate jar and imported that jar in both, but one works, the other don't. Same version of sbt, dependencies, application.conf, build.sbt and so on, but i couldn't figure out the problem. 
I tried with an `sbt clean` and removing all the inputs, but without any luck. 

I share here the trace from the terminal

```
 GetUpdates failed
org.json4s.package$MappingException: unknown error
	at org.json4s.Extraction$.extract(Extraction.scala:43)
	at org.json4s.ExtractableJsonAstNode.extract(ExtractableJsonAstNode.scala:21)
	at info.mukel.telegrambot4s.marshalling.JsonMarshallers.fromJson(JsonMarshallers.scala:59)
	at info.mukel.telegrambot4s.marshalling.JsonMarshallers.fromJson$(JsonMarshallers.scala:59)
	at info.mukel.telegrambot4s.marshalling.JsonMarshallers$.fromJson(JsonMarshallers.scala:96)
	at info.mukel.telegrambot4s.marshalling.AkkaHttpMarshalling$.$anonfun$camelCaseJsonUnmarshaller$1(AkkaHttpMarshalling.scala:16)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$map$1(FastFuture.scala:23)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.json4s.reflect.Executable.invoke(Executable.scala:52)
	at org.json4s.Extraction$ClassInstanceBuilder.instantiate(Extraction.scala:554)
	at org.json4s.Extraction$ClassInstanceBuilder.result(Extraction.scala:597)
	at org.json4s.Extraction$.$anonfun$extract$9(Extraction.scala:400)
	at org.json4s.Extraction$.customOrElse(Extraction.scala:606)
	at org.json4s.Extraction$.extract(Extraction.scala:392)
	at org.json4s.Extraction$CollectionBuilder.$anonfun$mkCollection$1(Extraction.scala:410)
	at scala.collection.immutable.List.map(List.scala:286)
	at org.json4s.Extraction$CollectionBuilder.mkCollection(Extraction.scala:410)
	at org.json4s.Extraction$CollectionBuilder.result(Extraction.scala:443)
	at org.json4s.Extraction$.$anonfun$extract$8(Extraction.scala:382)
	at org.json4s.Extraction$.customOrElse(Extraction.scala:606)
	at org.json4s.Extraction$.extract(Extraction.scala:382)
	at org.json4s.Extraction$.$anonfun$extract$6(Extraction.scala:366)
	at scala.Option.flatMap(Option.scala:188)
	at org.json4s.Extraction$.$anonfun$extract$5(Extraction.scala:366)
	at org.json4s.Extraction$.customOrElse(Extraction.scala:606)
	at org.json4s.Extraction$.extract(Extraction.scala:366)
	at org.json4s.Extraction$ClassInstanceBuilder.buildCtorArg(Extraction.scala:514)
	at org.json4s.Extraction$ClassInstanceBuilder.$anonfun$instantiate$4(Extraction.scala:546)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.json4s.Extraction$ClassInstanceBuilder.instantiate(Extraction.scala:546)
	at org.json4s.Extraction$ClassInstanceBuilder.result(Extraction.scala:597)
	at org.json4s.Extraction$.$anonfun$extract$9(Extraction.scala:400)
	at org.json4s.Extraction$.customOrElse(Extraction.scala:606)
	at org.json4s.Extraction$.extract(Extraction.scala:392)
	at org.json4s.Extraction$.extract(Extraction.scala:39)
	... 14 common frames omitted
Caused by: java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:268)
	at info.mukel.telegrambot4s.models.Update.<init>(Update.scala:44)
	... 51 common frames omitted
```

If you need something else, like the json exchanged, just tell me how to fetch it and I do it ASAP

**Comment by mukel** [comment]
There's a `.require` sanity check to avoid empty updates, in recent version there's an additional `poll` field in Update, so if you receive a poll update it will fail. Check [Update v4](https://github.com/bot4s/telegram/blob/master/core/src/com/bot4s/telegram/models/Update.scala) vs [Update v3](https://github.com/bot4s/telegram/blob/v3/core/src/main/scala/info/mukel/telegrambot4s/models/Update.scala).
Removing the `.require` should fix the issue; but I'd recommend to update to v4; the API changes are mostly cosmetic + FP-ification.

**Comment by ebenini-mdsol** [comment]
Thanks for the quick reply, the weird thing is that it works for one of the two bots. Anyway, I wait for it to be solved since the require still holds in v4 as well.

Regarding updating ,I was waiting for a proper release, instead of a pre-release, before migrating.

**Comment by benkio** [comment]
Thanks for the quick reply, the weird thing is that it works for one of the two bots. Anyway, I wait for it to be solved since the require still holds in v4 as well.

Regarding updating ,I was waiting for a proper release, instead of a pre-release, before migrating.

**Comment by mukel** [comment]
Then please stay tuned I'll be releasing the next RC with Scala 2.13 support soonish.
